import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#2a1700',
        'secondary-fixed': '#e9ddff',
        'on-primary': '#472a00',
        'tertiary': '#56e5a9',
        'primary-container': '#f59e0b',
        'inverse-surface': '#e7e0e8',
        'primary-fixed-dim': '#ffb95f',
        'secondary-container': '#571bc1',
        'surface-container': '#211f24',
        'on-secondary-container': '#c4abff',
        'surface-bright': '#3b383e',
        'surface-container-high': '#2c292e',
        'on-primary-container': '#613b00',
        'background': '#151218',
        'surface-container-lowest': '#0f0d12',
        'on-error-container': '#ffdad6',
        'surface-variant': '#363439',
        'on-surface': '#e7e0e8',
        'inverse-primary': '#855300',
        'surface': '#151218',
        'on-tertiary-fixed': '#002113',
        'surface-dim': '#151218',
        'error-container': '#93000a',
        'secondary-fixed-dim': '#d0bcff',
        'tertiary-fixed-dim': '#4edea3',
        'surface-container-low': '#1d1b20',
        'on-tertiary': '#003824',
        'inverse-on-surface': '#322f35',
        'surface-tint': '#ffb95f',
        'on-surface-variant': '#d8c3ad',
        'on-secondary-fixed-variant': '#5516be',
        'secondary': '#d0bcff',
        'primary': '#ffc174',
        'on-background': '#e7e0e8',
        'on-tertiary-container': '#004e34',
        'on-tertiary-fixed-variant': '#005236',
        'error': '#ffb4ab',
        'outline': '#a08e7a',
        'on-primary-fixed-variant': '#653e00',
        'on-secondary': '#3c0091',
        'on-error': '#690005',
        'tertiary-container': '#30c88f',
        'tertiary-fixed': '#6ffbbe',
        'outline-variant': '#534434',
        'on-secondary-fixed': '#23005c',
        'primary-fixed': '#ffddb8',
        'surface-container-highest': '#363439',
        // Legacy compatibility alias
        rpg: {
          dark: '#151218',
          card: '#211f24',
          border: '#363439',
          gold: '#f59e0b',
          xp: '#d0bcff',
          health: '#ef4444',
          accent: '#56e5a9',
        },
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'gutter': '1.25rem',
        'gutter-lg': '2rem',
        'margin': '1rem',
        'margin-md': '2rem',
        'margin-lg': '3.5rem',
      },
      fontFamily: {
        'label-telemetry': ['Space Grotesk', 'sans-serif'],
        'label-sigil': ['Noto Serif', 'serif'],
        'label-numeric': ['Space Grotesk', 'sans-serif'],
        'headline-xl': ['Noto Serif', 'serif'],
        'headline-lg': ['Noto Serif', 'serif'],
        'headline-md': ['Noto Serif', 'serif'],
        'headline-sm': ['Noto Serif', 'serif'],
        'title-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'title-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'label-telemetry': ['12px', { lineHeight: '16px', letterSpacing: '0.12em', fontWeight: '600' }],
        'label-numeric': ['14px', { lineHeight: '18px', letterSpacing: '0.05em', fontWeight: '700' }],
        'headline-xl': ['clamp(24px, 4.5vw, 40px)', { lineHeight: '1.25', letterSpacing: '0.03em', fontWeight: '700' }],
        'headline-lg': ['clamp(20px, 3.5vw, 32px)', { lineHeight: '1.3', letterSpacing: '0.02em', fontWeight: '600' }],
        'headline-md': ['clamp(18px, 2.5vw, 24px)', { lineHeight: '1.35', letterSpacing: '0.02em', fontWeight: '600' }],
        'headline-sm': ['clamp(16px, 2vw, 20px)', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '600' }],
        'title-lg': ['clamp(16px, 1.8vw, 18px)', { lineHeight: '1.4', fontWeight: '700' }],
        'title-md': ['clamp(14px, 1.5vw, 16px)', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-sigil': ['11px', { lineHeight: '14px', letterSpacing: '0.18em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};

export default config;
